import type { Metadata } from "next";
import { Public_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";  

const heading = Noto_Serif({
	variable: "--font-heading",
	subsets: ["latin"],
});
const body = Public_Sans({ subsets: ["latin"], variable: "--font-body" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={cn("h-full antialiased font-mono", heading.variable, body.variable)}>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
