import type { Metadata } from "next";
import { Public_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const heading = Noto_Serif({
	variable: "--font-heading",
	subsets: ["latin"],
});
const body = Public_Sans({ subsets: ["latin"], variable: "--font-body" });

export const metadata: Metadata = {
	title: { default: "Logo", template: "Logo | %s" },
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: { locales: "es" | "en" };
}>) {
	const { locales } = params;
	return (
		<html lang={locales} className={cn("h-full antialiased font-mono", heading.variable, body.variable)}>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
